[server]
port = 8501
address = "0.0.0.0"
headless = false
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"